name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-modules-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Extract commit IDs
        id: extract_args
        run: |
          COMMITS=$(git log --pretty=format:"%H" ${{ github.event.before }}..${{ github.event.after }})
          ARGS=""
          for COMMIT in $COMMITS; do
            DIFF=$(git show $COMMIT -- src/assets/modules.json || true)
            NEW_KEYS=$(echo "$DIFF" | grep '^+' | grep '"key"' | sed -E 's/.*"key": *"([^"]+)".*/\1/' || true)
            ARGS="$ARGS $NEW_KEYS"
          done
          ARGS=$(echo "$ARGS" | tr -s ' ')
          echo $ARGS
          echo "commit_args=$ARGS" >> $GITHUB_OUTPUT

      - name: Set up Python
        if: steps.extract_args.outputs.commit_args != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: steps.extract_args.outputs.commit_args != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Run api build
        if: steps.extract_args.outputs.commit_args != ''
        run: |
          python api build

      - name: Commit data
        if: steps.extract_args.outputs.commit_args != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update modules data

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: update-modules-data
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          BASE_URL: ${{ vars.BASE_URL }}
        run: npm run build

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
